### ISSUE TITLE
feat: Clean Room Service should spin up a Trusted Container(Simulated) with ZetaSQL engine running inside the enclave

### ISSUE THREAD

**Issue by qascade** [qascade/dcr#21]
## Description
Implement a Dockerfile that generates a Linux-sgx container with a ZetaSQL engine inside an enclave. We also need a container server inside the enclave that acts as a gateway between ZetaSQL and the Clean Room Service. This server is under development in issue: #20 by @qascade and @ShisuiMadara. 

spec doc: <https://www.notion.so/Solution-3-07d81059daab40cb84180336a33c3dd9> under Trusted Env section.  

## How are you planning to resolve on this issue?
TBD. Please write it in the spec docs and get it signed off.

**Comment by tipped73** [comment]
ZetaSql engine doesnot have any examples where they use join queries. ZetaSql is not building as well. We may have to look into the possibility of modifying the zetasql examples after resolving the build issues.

**Comment by qascade** [comment]
This issue has been discussed. We may need to build our own custom solution on supporting DP SQL queries as a transformation in dcr.

**Comment by qascade** [comment]
Closing this as completed in a separate repo
