### ISSUE TITLE
Improving the readme file of this project 

### ISSUE THREAD

**Issue by harshsingh32** [qascade/dcr#44]
## Description
Add description of issue here. 
I would like to improve the readme file of this project making it engaging for the users and make it more expressive.

## Screenshots
Put any screenshot(s) here.

## How are you planning to resolve on this issue?
Introducing few code changes
Making changes in the readme file and improving the file.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by qascade** [comment]
Hey, @harshsingh32 thanks for your enthusiasm. Currently no issues are being assigned until GSSoC Mentors are onboarded. That should happen by EOD. Then I will start assigning the issues. You can start looking at the code and the spec docs and try to understand the project in the meanwhile.

**Comment by qascade** [comment]
As per latest guidelines any doc changes are subject to a specific PR only. Any other changes are to be done by Code Owners. So closing this issue.
