### ISSUE TITLE
doc(readme): add contributors graph

### ISSUE THREAD

**Issue by S-ishita** [qascade/dcr#56]
## Description
I want to add contributors graph in readme

## Screenshots
Put any screenshot(s) here.

## Are you raising this PR under GSSoC'23? 
Yes

## How are you planning to resolve on this issue?
Introducing few code changes in readme file

**Comment by qascade** [comment]
@S-ishita Thanks for the suggestion and for volunteering for this issue. Please do the needful. I will review once you raise a PR. Name the branch. `doc.contributors_graph` .  Make sure you read commit conventions/guidelines that this project follow and add commit messages according to the spec. 
You can also add other things, that may make the readme visually better. Unwanted things can be reviewed during code review and removed accordingly.

**Comment by S-ishita** [comment]
PLease add me as assignee as well
