### ISSUE TITLE
Add 'Back-to-top' link in ReadMe.md

### ISSUE THREAD

**Issue by VSatwika** [qascade/dcr#63]
## Description
I would like to add a 'back-to-top' link in ReadMe.md
Adding a back-to-top will make navigation easier. 

## Are you raising this PR under GSSoC'23? 
Yes

**Comment by qascade** [comment]
The Read me is already so small. Back to top seems overkill

**Comment by VSatwika** [comment]
> The Read me is already so small. Back to top seems overkill

Okay.😅
